version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - cd docs/source && sphinx-build -b html . ../../_build/html

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
  - epub